branch-defaults:
  master:
    environment: Studentpals-dev
    group_suffix: null
environment-defaults:
  launchpad-dev:
    branch: null
    repository: null
global:
  application_name: StudentPals
  branch: master
  default_ec2_keyname: ollie
  default_platform: Corretto 11 running on 64bit Amazon Linux 2
  default_region: eu-west-1
  deploy:
    artifact: app.jar
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application

