version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - mvn test
  build:
    commands:
      - mvn clean package
  post_build:
    commands:
      - mv target/*.jar app.jar
artifacts:
  files:
    - app.jar